### ISSUE TITLE
Conditional validation

### ISSUE THREAD

**Issue by andrei-ivanov** [alfred82santa/dirty-validators#23]
Hi,
I'm trying to apply a validation limit based on the result of an expression and I can't find a way to do it.
So, instead of a static `Length(min=14, max=16)`, maybe the validator can be the result of a lambda?

**Comment by alfred82santa** [comment]
Hi Andrei,
currently it is not possible. But it could be cool to have a new validator, perhaps "Lambda" or "Function", which use a function to validate. 
On the other hand, if you mean you want to define min or max argument as a lambda it is a little bit more complicate. I should think about. It is not easy. There are some validators which can be used as conditions. I mean: "I want to limit to 5 if field "x" is True". 
https://github.com/alfred82santa/dirty-validators/blob/master/dirty_validators/complex.py#L254

When I coded this library I was thinking on static validations. I wanted to use them to create automatic documentation. I did with models, but I didn't with validations.

**Comment by andrei-ivanov** [comment]
Hmm, what I need is to have something like this:
- if entity is not yet persisted, the limit is 10
- if entity is persistent, the limit is 15

Or something like that, not sure how I would put that in an expression anyway :-)
Maybe with an artificial field "x" and use it to mark the operation type...

**Comment by alfred82santa** [comment]
I guess if entity is persisted it has an "id" field filled, don't it?
In this case, you could use:

```python
your_field = Required(validators=[IfField(field_name='id', 
                                                                field_validator=NotEmpty(), 
                                                                validator=Length(max=15)), 
                                                     IfField(field_name='id', 
                                                                field_validator=Empty(), 
                                                                validator=Length(max=10))]) 
```
